global:
  flow_name: ReadMapping
  parallelize: true
  log_dir: /work/log/ReadMapping
  output_dir: /work/output/01_ReadMapping

nodes:
  - id: 1
    tool: bwa
    subcommand: index
    input_dir:
      - reference: /work/input/ref
    output_dir: /work/output/01_ReadMapping/01_Indexing
    log_dir: /work/log/ReadMapping
    params:
      - bwa_path: "bwa"
      - threads: 20
      - reference: "/work/input/ref/cow.chr1.fa"
      - prefix: "ref"

  - id: 2
    tool: bwa
    subcommand: mem
    input_dir:
      - base: /work/output/00_ReadQC/TrimmedData
    output_dir: /work/output/01_ReadMapping/02_Mapping
    log_dir: /work/log/ReadMapping
    parallelize: true
    dependencies:
      - 1
    params:
      - bwa_path: "bwa"
      - threads: 4
      - index_prefix: /work/output/01_ReadMapping/01_Indexing/ref
      - platform: "ILLUMINA"
      - breeds: ["Angus", "Hanwoo", "Holstein", "Jersey", "Simmental"]
      - samples: ["1", "2", "3", "4", "5"]

  - id: 3
    tool: samtools
    subcommand: sort
    input_dir:
      - input_sam: /work/output/01_ReadMapping/02_Mapping
    output_dir: /work/output/01_ReadMapping/02_Mapping
    log_dir: /work/log/ReadMapping
    parallelize: true
    dependencies:
      - 2
    params:
      - samtools_path: "samtools"
      - threads: 4
      - breeds: ["Angus", "Hanwoo", "Holstein", "Jersey", "Simmental"]
      - samples: ["1", "2", "3", "4", "5"]

  - id: 4
    tool: picard
    subcommand: mark_duplicates
    input_dir:
      - input_bam: /work/output/01_ReadMapping/02_Mapping
    output_dir: /work/output/01_ReadMapping/03_Dedup
    log_dir: /work/log/ReadMapping
    parallelize: true
    dependencies:
      - 3
    params:
      - java_path: "java"
      - picard_path:  "/opt/picard.jar"
      - memory: 4
      - breeds: ["Angus", "Hanwoo", "Holstein", "Jersey", "Simmental"]
      - samples: ["1", "2", "3", "4", "5"]

  - id: 5
    tool: picard
    subcommand: add_read_groups
    input_dir:
      - input_bam: /work/output/01_ReadMapping/03_Dedup
    output_dir: /work/output/01_ReadMapping/03_Dedup
    log_dir: /work/log/ReadMapping
    parallelize: true
    dependencies:
      - 4
    params:
      - java_path: "java"
      - picard_path:  "/opt/picard.jar"
      - memory: 4
      - platform: "ILLUMINA"
      - platform_unit: "UNIT1"
      - breeds: ["Angus", "Hanwoo", "Holstein", "Jersey", "Simmental"]
      - samples: ["1", "2", "3", "4", "5"]