global:
  output_dir: /work/output/00_ReadQC
  log_dir: /work/log/ReadQC
  flow_name: ReadQC
  parallel : true
nodes:
  - id: 1
    tool: fastqc
    subcommand: fastqc
    input_dir:
      - fastq: /work/input/fq
    output_dir: /work/output/00_ReadQC/QC_Report_Before_Trimming
    log_dir: /work/log/ReadQC
    params:
      - fastqc_path: fastqc
      - threads: 4
      - flag: 0
      - file_pattern: '*.fastq*'

  - id: 2
    tool: multiqc
    subcommand: multiqc
    input_dir: /work/output/00_ReadQC/QC_Report_Before_Trimming
    output_dir: /work/output/00_ReadQC/QC_Report_Before_Trimming
    log_dir: /work/log/ReadQC
    dependencies:
      - 1
    params:
      - multiqc_path: multiqc

  - id: 3
    tool: trim_galore
    subcommand: trim_galore
    input_dir:
      - fastq: /work/input/fq
    output_dir: /work/output/00_ReadQC/TrimmedData
    log_dir: /work/log/ReadQC
    params:
      - trim_galore_path: trim_galore
      - cores: 4
      - additional_params: ""
      - paired_pattern: '*_1.*'


  - id: 4
    tool: fastqc
    subcommand: fastqc
    input_dir:
      - trimmed_data: /work/output/00_ReadQC/TrimmedData
    output_dir: /work/output/00_ReadQC/QC_Report_After_Trimming
    log_dir: /work/log/ReadQC
    dependencies:
      - 3
    params:
      - fastqc_path: fastqc
      - threads: 8
      - flag: 1
      - file_pattern: '*_val_*.fq.gz'

  - id: 5
    tool: multiqc
    subcommand: multiqc
    parallelize : true
    input_dir: /work/output/00_ReadQC/QC_Report_After_Trimming
    output_dir: /work/output/00_ReadQC/QC_Report_After_Trimming
    log_dir: /work/log/ReadQC
    dependencies:
      - 4
    params:
      - multiqc_path: multiqc

