global:
  flow_name: ReadQC
  parallel : true
nodes:
  - id: 1
    tool: fastqc
    subcommand: fastqc
    input_dir:
      - fastq: /home/wu/RUN_DOCKER/data/input
    output_dir: /home/wu/RUN_DOCKER/out1/00_ReadQC/QC_Report_Before_Trimming
    params:
      - fastqc_path: /home/wu/FastQC/fastqc
      - threads: 4
      - flag: 0
      - file_pattern: '*.fastq*'

  - id: 2
    tool: multiqc
    subcommand: multiqc
    input_dir: /home/wu/RUN_DOCKER/out1/00_ReadQC/QC_Report_Before_Trimming
    output_dir: /home/wu/RUN_DOCKER/out1/00_ReadQC/QC_Report_Before_Trimming
    dependencies:
      - 1
    params:
      - multiqc_path: multiqc

  - id: 3
    tool: trim_galore
    subcommand: trim_galore
    input_dir:
      - fastq: /home/wu/RUN_DOCKER/data/input
    output_dir: /home/wu/RUN_DOCKER/out1/00_ReadQC/TrimmedData
    params:
      - trim_galore_path: /home/wu/TrimGalore-0.6.10/trim_galore
      - cores: 4
      - additional_params: ""
      - paired_pattern: '*_1.*'


  - id: 4
    tool: fastqc
    subcommand: fastqc
    input_dir:
      - trimmed_data: /home/wu/RUN_DOCKER/out1/00_ReadQC/TrimmedData
    output_dir: /home/wu/RUN_DOCKER/out1/00_ReadQC/QC_Report_After_Trimming
    dependencies:
      - 3
    params:
      - fastqc_path: /home/wu/FastQC/fastqc
      - threads: 8
      - flag: 1
      - file_pattern: '*_val_*.fq.gz'

  - id: 5
    tool: multiqc
    subcommand: multiqc
    parallelize : true
    input_dir: /home/wu/RUN_DOCKER/out1/00_ReadQC/QC_Report_After_Trimming
    output_dir: /home/wu/RUN_DOCKER/out1/00_ReadQC/QC_Report_After_Trimming
    dependencies:
      - 4
    params:
      - multiqc_path: multiqc

