global:
  flow_name: variant_calling
  parallel : true
  log_dir: /work/log/variant_calling
  output_dir: /work
nodes:
  - id: 1
    name: faidx
    input_dir:
      - reference: /work/input/ref
    output_dir: /work/input/ref
    log_dir: /work/log/variant_calling
    tool: samtools
    params:
      - samtools_path: samtools
      - reference: cow.chr1.fa
      - tool_path: samtools

  - id: 2
    name: create_sequence_dictionary
    input_dir:
      - reference: /work/input/ref
    output_dir: /work/input/ref
    log_dir: /work/log/variant_calling
    tool: picard
    params:
      - java_path: java
      - picard_path: /opt/picard.jar
      - reference: cow.chr1.fa

  - id: 3
    name: local_realignment
    input_dir:
      - bam: /work/output/01
    output_dir: /work/output/01
    log_dir: /work/log/variant_calling
    tool: samtools
    params:
      - tool_path: samtools
      - th: "5"

  - id: 4
    name: haplotype_caller
    parallelize: true
    tool: gatk
    input_dir:
      - bam: /work/output/01
      - reference: /work/input/ref
    params:
      - java_path: java
      - memory: "20"
      - tool_path: gatk
      - th: "5"
      - reference: cow.chr1.fa
    output_dir: /work/output/02
    log_dir: /work/log/variant_calling
    dependencies:
      - 1
      - 2
      - 3

  - id: 5
    name: combine_gvcfs
    tool: gatk
    input_dir:
      - reference: /work/input/ref
      - gvcf: /work/output/02
    params:
      - java_path: java
      - memory: "20"
      - vcf_prefix: test
      - tool_path: gatk
      - reference: cow.chr1.fa
    output_dir: /work/output/02
    log_dir: /work/log/variant_calling
    dependencies:
      - 4

  - id: 6
    name: genotyping
    tool: gatk
    input_dir:
      - reference: /work/input/ref
      - vcf: /work/output/02
    params:
      - java_path: java
      - memory: "20"
      - tool_path: gatk
      - vcf_prefix: test
      - reference: cow.chr1.fa
    log_dir: /work/log/variant_calling
    output_dir: /work/output/02
    dependencies:
      - 5

  - id: 7
    name: varint_selection
    tool: gatk
    input_dir:
      - reference: /work/input/ref
      - vcf: /work/output/02
    log_dir: /work/log/variant_calling
    output_dir: /work/output/02
    params:
      - reference: cow.chr1.fa
      - vcf_prefix: test
      - java_path: java
      - tool_path: gatk
      - memory: "10"
    dependencies:
      - 6

  - id: 8
    name: variant_filtering
    tool: gatk
    input_dir:
      - reference: /work/input/ref
      - vcf: /work/output/02
    log_dir: /work/log/variant_calling
    output_dir: /work/output/02
    params:
      - reference: cow.chr1.fa
      - vcf_prefix: test
      - java_path: java
      - tool_path: gatk
      - memory: "10"
      - filter_expression: default
    dependencies:
      - 7

  - id: 9
    name: select_variants
    tool: gatk
    input_dir:
      - reference: /work/input/ref
      - vcf: /work/output/02
    log_dir: /work/log/variant_calling
    output_dir: /work/output/02
    params:
      - reference: cow.chr1.fa
      - vcf_prefix: test
      - java_path: java
      - tool_path: gatk
      - memory: "10"
    dependencies:
      - 8







