global:
  parallel : true

nodes:
  - name: ReadQC
    tool: fastqc
    input_dir: C:\Users\fate\source\repos
    dependencies :
    params:
      - fastqc_path : fastqc


  - name: ReadMapping
    tool: bwa
    dependencies : ReadQC
    input_dir: C:\Users\fate\source\repos
    params:
      - OPTION : 1

  - name: VariantCalling
    tool: bcftools
    input_dir: C:\Users\fate\source\repos
    dependencies:
      - ReadMapping
      - ReadQC
    parallel : true
    params:
      - option: 1
